# Generated by Django 6.1.1 on 2026-09-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_category_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(default='S, M, L, XL', help_text='المقاسات المتوفرة مفصولة بفواصل (مثال: S, M, L أو 40, 41, 42)', max_length=200),
        ),
    ]
